const provincesData = {
  ardabil: 11,
  isfahan: 24,
  alborz: 7,
  ilam: 14,
  eastAzerbaijan: 21,
  westAzerbaijan: 17,
  bushehr: 10,
  tehran: 17,
  chaharmahalandBakhtiari: 10,
  southKhorasan: 11,
  razaviKhorasan: 28,
  northKhorasan: 8,
  khuzestan: 27,
  zanjan: 9,
  semnan: 9,
  sistanAndBaluchestan: 19,
  fars: 26,
  qazvin: 6,
  qom: 1,
  kurdistan: 10,
  kerman: 25,
  kohgiluyehAndBoyerAhmad: 9,
  kermanshah: 14,
  golestan: 14,
  gilan: 16,
  lorestan: 12,
  mazandaran: 23,
  markazi: 13,
  hormozgan: 12,
  hamadan: 9,
  yazd: 10,
};

export default provincesData;
